### ISSUE TITLE
Possible to change executable name to "cnf"?

### ISSUE THREAD

**Issue by samduanx** [vyskocilm/cnf-rs#21]
First of all, thanks for your effort to port cnf to Rust! The problem is that openSUSE (at least Tumbleweed) **replaces** the original cnf with cnf-rs currently, and executing "cnf" comes with a "command not found" error. Changing the executable's name to cnf will ease the users from finding it, so a user wouldn't need a link or an alias to cnf anymore.

**Comment by vyskocilm** [comment]
Hi, thanks for a report - the naming is hard apparently and `cnf-rs` is not the nicest name. I somehow though it will live together with an existing handler, but this is not possible/practical anyway.

Fixed in utilities/cnf-rs for now: https://build.opensuse.org/package/rdiff/utilities/cnf-rs?linkrev=base&rev=6 and will push it into Factory once my previous request will get accepted.

**Comment by samduanx** [comment]
OK, thanks! Really appreciate it.

**Comment by vyskocilm** [comment]
Got the same request because of openQA test fail. Sent to Factory via https://build.opensuse.org/request/show/1112720

**Comment by samduanx** [comment]
Update has been pushed to user, as I can confirm on my laptop with Tumbleweed. Thanks and I'll close the issue.
